// Code generated by counterfeiter. DO NOT EDIT.
package aviatorfakes

import (
	"os/exec"
	"sync"

	"github.com/JulzDiverse/aviator"
)

type FakeExecutor struct {
	CommandStub        func(interface{}) ([]*exec.Cmd, error)
	commandMutex       sync.RWMutex
	commandArgsForCall []struct {
		arg1 interface{}
	}
	commandReturns struct {
		result1 []*exec.Cmd
		result2 error
	}
	commandReturnsOnCall map[int]struct {
		result1 []*exec.Cmd
		result2 error
	}
	ExecuteStub        func([]*exec.Cmd) error
	executeMutex       sync.RWMutex
	executeArgsForCall []struct {
		arg1 []*exec.Cmd
	}
	executeReturns struct {
		result1 error
	}
	executeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeExecutor) Command(arg1 interface{}) ([]*exec.Cmd, error) {
	fake.commandMutex.Lock()
	ret, specificReturn := fake.commandReturnsOnCall[len(fake.commandArgsForCall)]
	fake.commandArgsForCall = append(fake.commandArgsForCall, struct {
		arg1 interface{}
	}{arg1})
	fake.recordInvocation("Command", []interface{}{arg1})
	fake.commandMutex.Unlock()
	if fake.CommandStub != nil {
		return fake.CommandStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.commandReturns.result1, fake.commandReturns.result2
}

func (fake *FakeExecutor) CommandCallCount() int {
	fake.commandMutex.RLock()
	defer fake.commandMutex.RUnlock()
	return len(fake.commandArgsForCall)
}

func (fake *FakeExecutor) CommandArgsForCall(i int) interface{} {
	fake.commandMutex.RLock()
	defer fake.commandMutex.RUnlock()
	return fake.commandArgsForCall[i].arg1
}

func (fake *FakeExecutor) CommandReturns(result1 []*exec.Cmd, result2 error) {
	fake.CommandStub = nil
	fake.commandReturns = struct {
		result1 []*exec.Cmd
		result2 error
	}{result1, result2}
}

func (fake *FakeExecutor) CommandReturnsOnCall(i int, result1 []*exec.Cmd, result2 error) {
	fake.CommandStub = nil
	if fake.commandReturnsOnCall == nil {
		fake.commandReturnsOnCall = make(map[int]struct {
			result1 []*exec.Cmd
			result2 error
		})
	}
	fake.commandReturnsOnCall[i] = struct {
		result1 []*exec.Cmd
		result2 error
	}{result1, result2}
}

func (fake *FakeExecutor) Execute(arg1 []*exec.Cmd) error {
	var arg1Copy []*exec.Cmd
	if arg1 != nil {
		arg1Copy = make([]*exec.Cmd, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.executeMutex.Lock()
	ret, specificReturn := fake.executeReturnsOnCall[len(fake.executeArgsForCall)]
	fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
		arg1 []*exec.Cmd
	}{arg1Copy})
	fake.recordInvocation("Execute", []interface{}{arg1Copy})
	fake.executeMutex.Unlock()
	if fake.ExecuteStub != nil {
		return fake.ExecuteStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.executeReturns.result1
}

func (fake *FakeExecutor) ExecuteCallCount() int {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return len(fake.executeArgsForCall)
}

func (fake *FakeExecutor) ExecuteArgsForCall(i int) []*exec.Cmd {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return fake.executeArgsForCall[i].arg1
}

func (fake *FakeExecutor) ExecuteReturns(result1 error) {
	fake.ExecuteStub = nil
	fake.executeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeExecutor) ExecuteReturnsOnCall(i int, result1 error) {
	fake.ExecuteStub = nil
	if fake.executeReturnsOnCall == nil {
		fake.executeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.executeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeExecutor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.commandMutex.RLock()
	defer fake.commandMutex.RUnlock()
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeExecutor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ aviator.Executor = new(FakeExecutor)
